SELECT * FROM public.customer
LIMIT 100

-- What is the total revenue generated by male vs. female customers
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

-- Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >=  (SELECT AVG(purchase_amount) from customer)

-- Which are the top 5 product with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

-- Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount::numeric),2) as "Average Purchase Amount"
from customer
where shipping_type in('Standard', 'Express')
group by shipping_type

-- Do Subscribed customers spend more? Compare average spend and total revenue between subscriber and non-sub
select subscription_status, ROUND(AVG(purchase_amount::numeric),2) as "Average Spend", SUM(purchase_amount) as "Total Revenue"
from customer 
group by subscription_status
order by "Total Revenue", "Average Spend" desc

-- Which 5 products have the highest percentage of purchases with discount applied?
SELECT
  item_purchased,
  COUNT(*) AS total_purchases,
  SUM(CASE 
	WHEN discount_applied = 'Yes' THEN 1
	ELSE 0 END) AS discount_purchases,
  ROUND(SUM(CASE 
	WHEN discount_applied = 'Yes' THEN 1
	ELSE 0 END) * 100.0 / COUNT(*), 2) AS discount_percentage
FROM customer
GROUP BY item_purchased
ORDER BY discount_percentage DESC
LIMIT 5;

-- Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and
-- show the count of each segment.
-- using CTE
with customer_type as(
	select customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 and 10 THEN 'Returning'
		ELSE 'Loyal'
	END AS customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

-- What are the top 3 most purchased products within each category
with item_counts as(
	select category, item_purchased, COUNT(customer_id) as total_orders,
	ROW_NUMBER() over(partition by category order by count(customer_id) DESC) as item_rank
	from customer
	group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3

-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- What is the revenue contribution of each age group
select age_group,
SUM(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc